language: go
go:
- 1.6

env:
  global:
      - DEPLOY_HOST=rpm.palette-software.net
      - DEPLOY_PATH=/home/palette-rpm/rpm_repo
      - DEPLOY_USER=palette-rpm

      # travis encrypt DEPLOY_PASSWORD=...
      - secure: "QRZhThXmVMOMfktlgfNaSAdxNX8FUMq3AMLTyWy3H3KoK8VkgBgsovtorR2tysm6IWH6AsJimwEoMiL+0h1FIKdEt9CkwSPbFke1h/sk3CkFVkNm3XQvEkPYnVX/7p2Tb0frZc1b0q3D6yXv5Fb8Osml56qeClMNQmJ2l7vbwiGCGahH9o/tLCUiatx5wzdxVHKxWlSG95YDw136KX7Z5Bm0R3JEIsJjeyhM8gOWTP0mhn02I8k+lP1akDeqtPXtUp1iLRN0Ibr2GusFYb+DWRf0tn6dLbezaOX9Tu+r8EY7l93kx9B7z8JbB2Fq2eAdLNjfzSY/612p0lhNCJPkdD8i+0hG+am0vSCWXdz7JuqdknmXXj1QjVJUjZDDeL5y67KxHoruu0mIrrPMCKOKijWIL49Ry3k6VP65+nUCJn+vsD7yQXgQajLng2jqywUjQMbJQnB/G1d3Gv4F6rbz9+OMHF+1STA5uO5U+Nddv+wdZlve39c0M++ppND5donqdNiNdHkl92xJUORNVnrC6SDHimm9yq5vJOqcvYuHGAgtxWEYZXoQExXnckm9a3+fe/rC69lkh//HxkyqI0XCjKydIVcu+wVGlKueKpT7srBqJrdeVtO6avGFjeF/3PAO2FLXeZGANtUwF4g/p8cTRRWLuebfDg82ps4vzLMUCqw="

# install the RPM package
addons:
  apt:
    packages:
      - rpm
      # To deploy the rpms, we need to ssh into places, and we dont want to store keys for now
      - sshpass

before_install:
  # add the bindata generator
  - go get -u github.com/jteeuwen/go-bindata/...


# Put a proper version string into the version file
before_script:
  - export BUILD_TAG=$TRAVIS_BRANCH-$(date -u "+%Y-%m-%d-%H-%M-%S")-$TRAVIS_BUILD_NUMBER
  - echo "==== Setting ${BUILD_TAG} as version ===="
  - echo ${BUILD_TAG} > assets/VERSION

  # re-generate the assets after the version change
  - go generate -x github.com/palette-software/insight-server
  - cat assets.go



before_deploy:
  - export VERSION=$(echo $TRAVIS_TAG | grep -o '[0-9][0-9]*\.[0-9][0-9]*\.[0-9][0-9]*')
  - cd rpm-build

  # Create directories
  - mkdir -p etc/palette-insight-server
  - mkdir -p usr/local/bin

  # Copy the binary
  - cp -v $GOPATH/bin/server usr/local/bin/palette-insight-server
  - cp -v ../server/sample.config etc/palette-insight-server/server.config
  - echo "BUILDING VERSION:$VERSION"

  # build the rpm
  - rpmbuild -bb --buildroot $(pwd) --define "version $VERSION" --define "_rpmdir $(pwd)/_build" palette-insight-server.spec
  - cd ..
  - zip palette-insight-server-$(cat assets/VERSION).zip -j $GOPATH/bin/server

  # Upload the RPM to the RPM repository
  - export SSHPASS=$DEPLOY_PASS
  - sshpass -e scp -R rpm-build/_build/* $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH

deploy:
  provider: releases
  api_key:
    secure: SsFDMxXEMPWGfF/STq6Ik2XbVBI4bZHt9UbjRSN2Id8St5pdTSowSTCcGIHC42JTXfSPVUSSex4D4f/c5avISpqz5m3MWug6wR5da6QTJ16phlRWUlcFHIkwJGqtlkWXwGDBO1GGN1tpknmM9Q41p2QLkTM2ycq1TFCFSIs0J8HanBoYqjfl/JgVaYcZuUkP/XuB/PIS3HNgbwLit2zKBK/mxSNhb1D0GKKoHQXGKxC1OPjXa4z7AjwowqWLWH+3lMl3xtmIMjXg8xJRkWrw4Q6EH+iY9zqvAnOGqUrEtAN3KCVjV7c2+JBc/7ObRk4Zk9L4lJxZxAR5ZFbP8EwwlXiYF0Wxtpa9OxeaLpkHAxFGjeDZS6HzRKa0pU+Coc0ERll3ibZf5jehdLzQ7Q7N7AzXxtLSwChE+WYzEdGTLT7avar3ZieUy5t38+WPEEhPryDoh6GAAWCPctsnvoqeLUs+EO2qvxLqLfEXNth1tMx8tiNkB8KQtknCpUftmuvsJNXQtz8Qe4CDMfasfeecYTz3XauwtbjeDH65Xzc2UwBt6uRNdk3fuG4tnLyuVoTGCCM+uNk2AC/d1EXGJKzEU/bz/fTfim4/nD2jtDANN8Z7m/aHSJTIPoK60mL/OdyVtZT80Pq1Mo2XGBT90sS/Z45txiRAdK+u9KCJww/c9jo=
  file_glob: true
  file:
    - palette-insight-server-*.zip
    - rpm-build/_build/x86_64/*.rpm

  on:
    repo: palette-software/insight-server
  skip_cleanup: true
  on:
      tags: true
